export { PlatformShell, type PlatformShellProps } from "./platform-shell";
export { TopBar } from "./top-bar";
export { SideNav } from "./side-nav";
export { WorkspaceHeader, type WorkspaceHeaderProps } from "./workspace-header";
export { ShellBreadcrumbs } from "./shell-breadcrumbs";
export { ShellFooter } from "./shell-footer";
export { NotificationCentre } from "./notification-centre";
export { GlobalSearchDialog } from "./global-search";
export { UserMenu } from "./user-menu";
export { EmptyState, type EmptyStateProps } from "./empty-state";
export { ErrorPage, ERROR_COPY, type ErrorKind } from "./error-page";
export { navIcon } from "./icons";
