import type { ReportBranding } from "./types";

/**
 * BrandingService (pure half).
 *
 * Branding is resolved once per report and snapshotted onto the record, so a
 * historical version always renders with the branding it was generated under.
 */

export const DEFAULT_BRANDING: ReportBranding = {
  productName: "DeliveryIQ",
  logoText: "DIQ",
  logoUrl: null,
  primaryColour: "0EA5A4",
  secondaryColour: "6366F1",
  inkColour: "0F172A",
  mutedColour: "64748B",
  surfaceColour: "F8FAFC",
  headingFont: "Arial",
  bodyFont: "Arial",
  headerText: "DeliveryIQ Intelligence Platform",
  footerText: "Generated by DeliveryIQ",
  contactName: "",
  contactEmail: "",
  contactPhone: "",
  website: "",
  confidentialityStatement: "Confidential — for the intended recipient only.",
};

const HEX = /^[0-9a-f]{6}$/i;

/** Accepts `#0ea5a4`, `0EA5A4` or a 3-digit hex; falls back when unusable. */
export function normaliseColour(value: unknown, fallback: string): string {
  if (typeof value !== "string") return fallback;
  const trimmed = value.trim().replace(/^#/, "");
  const expanded =
    trimmed.length === 3
      ? trimmed
          .split("")
          .map((char) => char + char)
          .join("")
      : trimmed;
  return HEX.test(expanded) ? expanded.toUpperCase() : fallback;
}

function text(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

/** Merge partial (organisation) branding over the platform defaults. */
export function resolveBranding(
  overrides?: Partial<ReportBranding> | null,
  base: ReportBranding = DEFAULT_BRANDING,
): ReportBranding {
  const input = overrides ?? {};
  return {
    productName: text(input.productName, base.productName),
    logoText: text(input.logoText, base.logoText).slice(0, 6).toUpperCase(),
    logoUrl:
      typeof input.logoUrl === "string" && input.logoUrl.trim() ? input.logoUrl.trim() : base.logoUrl,
    primaryColour: normaliseColour(input.primaryColour, base.primaryColour),
    secondaryColour: normaliseColour(input.secondaryColour, base.secondaryColour),
    inkColour: normaliseColour(input.inkColour, base.inkColour),
    mutedColour: normaliseColour(input.mutedColour, base.mutedColour),
    surfaceColour: normaliseColour(input.surfaceColour, base.surfaceColour),
    headingFont: text(input.headingFont, base.headingFont),
    bodyFont: text(input.bodyFont, base.bodyFont),
    headerText: text(input.headerText, base.headerText),
    footerText: text(input.footerText, base.footerText),
    contactName: text(input.contactName, base.contactName),
    contactEmail: text(input.contactEmail, base.contactEmail),
    contactPhone: text(input.contactPhone, base.contactPhone),
    website: text(input.website, base.website),
    confidentialityStatement: text(input.confidentialityStatement, base.confidentialityStatement),
  };
}

/** Single-line footer combining branding footer, contact and confidentiality. */
export function footerLine(branding: ReportBranding): string {
  return [branding.footerText, branding.contactEmail, branding.confidentialityStatement]
    .filter(Boolean)
    .join("  •  ");
}
