import { escapeXml, zip, type ZipEntry } from "@/lib/dashboard/pptx.server";
import type { ReportDocument, ReportDocumentSection } from "../types";

/**
 * Microsoft Excel (.xlsx) renderer — dependency-free OOXML, Worker safe.
 *
 * Tabular blocks become real worksheets (one per section that contains data);
 * narrative blocks are written to a leading "Summary" sheet so an analyst gets
 * both the numbers and the context in one workbook.
 */

const encoder = new TextEncoder();

interface Sheet {
  name: string;
  rows: { value: string; style: number }[][];
  widths: number[];
}

const STYLE_DEFAULT = 0;
const STYLE_TITLE = 1;
const STYLE_HEADER = 2;
const STYLE_LABEL = 3;

function safeSheetName(name: string, used: Set<string>): string {
  const cleaned = name.replace(/[\\/*?:[\]]/g, " ").trim().slice(0, 28) || "Sheet";
  let candidate = cleaned;
  let counter = 2;
  while (used.has(candidate.toLowerCase())) candidate = `${cleaned.slice(0, 25)} ${counter++}`;
  used.add(candidate.toLowerCase());
  return candidate;
}

function columnRef(index: number): string {
  let ref = "";
  let value = index + 1;
  while (value > 0) {
    const remainder = (value - 1) % 26;
    ref = String.fromCharCode(65 + remainder) + ref;
    value = Math.floor((value - remainder) / 26);
  }
  return ref;
}

function isNumeric(value: string): boolean {
  return value !== "" && /^-?\d+(\.\d+)?$/.test(value.replace(/,/g, ""));
}

function sheetXml(sheet: Sheet): string {
  const cols = sheet.widths.length
    ? `<cols>${sheet.widths
        .map((width, index) => `<col min="${index + 1}" max="${index + 1}" width="${width}" customWidth="1"/>`)
        .join("")}</cols>`
    : "";

  const rows = sheet.rows
    .map((cells, rowIndex) => {
      const body = cells
        .map((cell, cellIndex) => {
          const ref = `${columnRef(cellIndex)}${rowIndex + 1}`;
          if (cell.value === "") return `<c r="${ref}" s="${cell.style}"/>`;
          if (isNumeric(cell.value) && cell.style === STYLE_DEFAULT) {
            return `<c r="${ref}" s="${cell.style}"><v>${Number(cell.value.replace(/,/g, ""))}</v></c>`;
          }
          return `<c r="${ref}" s="${cell.style}" t="inlineStr"><is><t xml:space="preserve">${escapeXml(cell.value)}</t></is></c>`;
        })
        .join("");
      return `<row r="${rowIndex + 1}">${body}</row>`;
    })
    .join("");

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">${cols}<sheetData>${rows}</sheetData></worksheet>`;
}

function buildSheets(document: ReportDocument): Sheet[] {
  const used = new Set<string>();
  const sheets: Sheet[] = [];

  const summary: Sheet = { name: safeSheetName("Summary", used), rows: [], widths: [38, 62] };
  const push = (label: string, value: string, style = STYLE_DEFAULT) =>
    summary.rows.push([
      { value: label, style: label ? STYLE_LABEL : STYLE_DEFAULT },
      { value, style },
    ]);

  summary.rows.push([{ value: document.cover.title, style: STYLE_TITLE }, { value: "", style: STYLE_DEFAULT }]);
  push("Organisation", document.cover.organisation);
  if (document.cover.workspace) push("Workspace", document.cover.workspace);
  push("Generated", new Date(document.cover.generatedAt).toUTCString());
  push("Generated by", document.cover.generatedBy);
  push("Version", `v${document.cover.version}`);
  push("Template", document.cover.templateName);
  push("", "");

  const tabular = (section: ReportDocumentSection) =>
    section.blocks.filter((block) => block.kind === "table" || block.kind === "chart" || block.kind === "kpis");

  for (const section of document.sections) {
    for (const block of section.blocks) {
      if (block.kind === "paragraph" || block.kind === "note") push(section.title, block.text);
      if (block.kind === "bullets") for (const item of block.items) push(section.title, item);
    }

    const dataBlocks = tabular(section);
    if (!dataBlocks.length) continue;

    const sheet: Sheet = { name: safeSheetName(section.title, used), rows: [], widths: [] };
    for (const block of dataBlocks) {
      if (block.kind === "table") {
        sheet.rows.push(block.columns.map((column) => ({ value: column, style: STYLE_HEADER })));
        for (const row of block.rows) {
          sheet.rows.push(row.map((cell) => ({ value: cell, style: STYLE_DEFAULT })));
        }
        sheet.widths = block.columns.map((column, index) =>
          Math.min(
            60,
            Math.max(
              12,
              column.length + 4,
              ...block.rows.map((row) => Math.min(60, (row[index] ?? "").length + 2)),
            ),
          ),
        );
      }
      if (block.kind === "kpis") {
        sheet.rows.push([
          { value: "Measure", style: STYLE_HEADER },
          { value: "Value", style: STYLE_HEADER },
        ]);
        for (const item of block.items) {
          sheet.rows.push([
            { value: item.label, style: STYLE_DEFAULT },
            { value: item.value, style: STYLE_DEFAULT },
          ]);
        }
        if (!sheet.widths.length) sheet.widths = [38, 20];
      }
      if (block.kind === "chart") {
        sheet.rows.push([
          { value: block.caption || "Series", style: STYLE_HEADER },
          { value: "Value", style: STYLE_HEADER },
        ]);
        for (const point of block.series) {
          sheet.rows.push([
            { value: point.label, style: STYLE_DEFAULT },
            { value: String(point.value), style: STYLE_DEFAULT },
          ]);
        }
        if (!sheet.widths.length) sheet.widths = [38, 20];
      }
      sheet.rows.push([]);
    }
    sheets.push(sheet);
  }

  return [summary, ...sheets];
}

/** Render a composed document into .xlsx bytes. */
export function renderXlsxDocument(document: ReportDocument): Uint8Array {
  const sheets = buildSheets(document);
  const brand = document.branding;

  const workbook = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets
    .map(
      (sheet, index) =>
        `<sheet name="${escapeXml(sheet.name)}" sheetId="${index + 1}" r:id="rId${index + 1}"/>`,
    )
    .join("")}</sheets></workbook>`;

  const workbookRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets
    .map(
      (_, index) =>
        `<Relationship Id="rId${index + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${index + 1}.xml"/>`,
    )
    .join("")}<Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;

  const styles = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="4"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="16"/><color rgb="FF${brand.inkColour}"/><name val="Arial"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Arial"/></font><font><b/><sz val="11"/><color rgb="FF${brand.mutedColour}"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF${brand.primaryColour}"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf xfId="0" fontId="0" fillId="0" borderId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf xfId="0" fontId="1" fillId="0" borderId="0" applyFont="1"/><xf xfId="0" fontId="2" fillId="2" borderId="0" applyFont="1" applyFill="1"/><xf xfId="0" fontId="3" fillId="0" borderId="0" applyFont="1"/></cellXfs></styleSheet>`;

  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets
    .map(
      (_, index) =>
        `<Override PartName="/xl/worksheets/sheet${index + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`,
    )
    .join("")}</Types>`;

  const rootRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;

  const entries: ZipEntry[] = [
    { name: "[Content_Types].xml", data: encoder.encode(contentTypes) },
    { name: "_rels/.rels", data: encoder.encode(rootRels) },
    { name: "xl/workbook.xml", data: encoder.encode(workbook) },
    { name: "xl/_rels/workbook.xml.rels", data: encoder.encode(workbookRels) },
    { name: "xl/styles.xml", data: encoder.encode(styles) },
    ...sheets.map((sheet, index) => ({
      name: `xl/worksheets/sheet${index + 1}.xml`,
      data: encoder.encode(sheetXml(sheet)),
    })),
  ];

  return zip(entries);
}
