import type { ReportBranding } from "./types";

/**
 * Report branding. Everything visual in a rendered artefact resolves from
 * here, so a customer-specific theme is a config change rather than a
 * renderer change. Colours are hex without `#` so the OOXML and PDF writers
 * can consume them directly.
 */
export const DEFAULT_BRANDING: ReportBranding = {
  productName: "DeliveryIQ",
  logoText: "DeliveryIQ",
  tagline: "Delivery intelligence, evidenced end to end",
  primary: "0EA5E9",
  accent: "22C55E",
  ink: "0F172A",
  muted: "64748B",
  surface: "F1F5F9",
  headingFont: "Arial",
  bodyFont: "Arial",
  footerNote: "Generated by the DeliveryIQ Intelligence Runtime — figures are traceable to source responses.",
};

const HEX = /^[0-9a-fA-F]{6}$/;

function colour(value: unknown, fallback: string): string {
  if (typeof value !== "string") return fallback;
  const cleaned = value.replace(/^#/, "").trim();
  return HEX.test(cleaned) ? cleaned.toUpperCase() : fallback;
}

function text(value: unknown, fallback: string, max = 160): string {
  if (typeof value !== "string") return fallback;
  const trimmed = value.trim();
  return trimmed ? trimmed.slice(0, max) : fallback;
}

/** Merge caller-supplied branding over the defaults, sanitising every field. */
export function resolveBranding(overrides?: Partial<ReportBranding> | null): ReportBranding {
  if (!overrides) return { ...DEFAULT_BRANDING };
  return {
    productName: text(overrides.productName, DEFAULT_BRANDING.productName, 60),
    logoText: text(overrides.logoText, DEFAULT_BRANDING.logoText, 40),
    tagline: text(overrides.tagline, DEFAULT_BRANDING.tagline, 120),
    primary: colour(overrides.primary, DEFAULT_BRANDING.primary),
    accent: colour(overrides.accent, DEFAULT_BRANDING.accent),
    ink: colour(overrides.ink, DEFAULT_BRANDING.ink),
    muted: colour(overrides.muted, DEFAULT_BRANDING.muted),
    surface: colour(overrides.surface, DEFAULT_BRANDING.surface),
    headingFont: text(overrides.headingFont, DEFAULT_BRANDING.headingFont, 40),
    bodyFont: text(overrides.bodyFont, DEFAULT_BRANDING.bodyFont, 40),
    footerNote: text(overrides.footerNote, DEFAULT_BRANDING.footerNote, 200),
  };
}
