/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgePacksIndexRouteImport } from './routes/knowledge-packs.index'
import { Route as SignalIdRouteImport } from './routes/signal.$id'
import { Route as ScoreIdRouteImport } from './routes/score.$id'
import { Route as RuntimeSignalsRouteImport } from './routes/runtime.signals'
import { Route as RuntimeScoresRouteImport } from './routes/runtime.scores'
import { Route as RuntimeRulesRouteImport } from './routes/runtime.rules'
import { Route as RuntimePatternsRouteImport } from './routes/runtime.patterns'
import { Route as RuntimeObservationsRouteImport } from './routes/runtime.observations'
import { Route as RuntimeNarrativeRouteImport } from './routes/runtime.narrative'
import { Route as RuleIdRouteImport } from './routes/rule.$id'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as PatternIdRouteImport } from './routes/pattern.$id'
import { Route as ObservationIdRouteImport } from './routes/observation.$id'
import { Route as NarrativeIdRouteImport } from './routes/narrative.$id'
import { Route as KnowledgePacksValidateRouteImport } from './routes/knowledge-packs.validate'
import { Route as KnowledgePacksReloadRouteImport } from './routes/knowledge-packs.reload'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'
import { Route as ApiAssessmentsRouteImport } from './routes/api/assessments'
import { Route as KnowledgePackIdIndexRouteImport } from './routes/knowledge-pack.$id.index'
import { Route as InternalSignalsIndexRouteImport } from './routes/internal.signals.index'
import { Route as InternalScoresIndexRouteImport } from './routes/internal.scores.index'
import { Route as InternalRulesIndexRouteImport } from './routes/internal.rules.index'
import { Route as InternalPatternsIndexRouteImport } from './routes/internal.patterns.index'
import { Route as InternalObservationsIndexRouteImport } from './routes/internal.observations.index'
import { Route as InternalNarrativesIndexRouteImport } from './routes/internal.narratives.index'
import { Route as InternalKnowledgePacksIndexRouteImport } from './routes/internal.knowledge-packs.index'
import { Route as AssessmentIdIndexRouteImport } from './routes/assessment.$id.index'
import { Route as ReportIdDownloadRouteImport } from './routes/report.$id.download'
import { Route as KnowledgePackIdVersionsRouteImport } from './routes/knowledge-pack.$id.versions'
import { Route as KnowledgePackIdActivateRouteImport } from './routes/knowledge-pack.$id.activate'
import { Route as InternalSignalsIdRouteImport } from './routes/internal.signals.$id'
import { Route as InternalScoresIdRouteImport } from './routes/internal.scores.$id'
import { Route as InternalRulesIdRouteImport } from './routes/internal.rules.$id'
import { Route as InternalPatternsIdRouteImport } from './routes/internal.patterns.$id'
import { Route as InternalObservationsIdRouteImport } from './routes/internal.observations.$id'
import { Route as InternalNarrativesIdRouteImport } from './routes/internal.narratives.$id'
import { Route as InternalKnowledgePacksIdRouteImport } from './routes/internal.knowledge-packs.$id'
import { Route as AssessmentIdSummaryRouteImport } from './routes/assessment.$id.summary'
import { Route as AssessmentIdSignalsRouteImport } from './routes/assessment.$id.signals'
import { Route as AssessmentIdScoresRouteImport } from './routes/assessment.$id.scores'
import { Route as AssessmentIdRulesRouteImport } from './routes/assessment.$id.rules'
import { Route as AssessmentIdResultsRouteImport } from './routes/assessment.$id.results'
import { Route as AssessmentIdReportsRouteImport } from './routes/assessment.$id.reports'
import { Route as AssessmentIdProcessingRouteImport } from './routes/assessment.$id.processing'
import { Route as AssessmentIdPatternsRouteImport } from './routes/assessment.$id.patterns'
import { Route as AssessmentIdObservationsRouteImport } from './routes/assessment.$id.observations'
import { Route as AssessmentIdNarrativeRouteImport } from './routes/assessment.$id.narrative'
import { Route as AssessmentIdDashboardRouteImport } from './routes/assessment.$id.dashboard'
import { Route as ApiAssessmentsIdRouteImport } from './routes/api/assessments.$id'
import { Route as AssessmentIdExportFormatRouteImport } from './routes/assessment.$id.export.$format'
import { Route as ApiAssessmentsIdSubmitRouteImport } from './routes/api/assessments.$id.submit'
import { Route as ApiAssessmentsIdStatusRouteImport } from './routes/api/assessments.$id.status'
import { Route as ApiAssessmentsIdRetryRouteImport } from './routes/api/assessments.$id.retry'
import { Route as ApiAssessmentsIdResultsRouteImport } from './routes/api/assessments.$id.results'
import { Route as ApiAssessmentsIdAdvanceRouteImport } from './routes/api/assessments.$id.advance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePacksIndexRoute = KnowledgePacksIndexRouteImport.update({
  id: '/knowledge-packs/',
  path: '/knowledge-packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalIdRoute = SignalIdRouteImport.update({
  id: '/signal/$id',
  path: '/signal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreIdRoute = ScoreIdRouteImport.update({
  id: '/score/$id',
  path: '/score/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeSignalsRoute = RuntimeSignalsRouteImport.update({
  id: '/runtime/signals',
  path: '/runtime/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeScoresRoute = RuntimeScoresRouteImport.update({
  id: '/runtime/scores',
  path: '/runtime/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRulesRoute = RuntimeRulesRouteImport.update({
  id: '/runtime/rules',
  path: '/runtime/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimePatternsRoute = RuntimePatternsRouteImport.update({
  id: '/runtime/patterns',
  path: '/runtime/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeObservationsRoute = RuntimeObservationsRouteImport.update({
  id: '/runtime/observations',
  path: '/runtime/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeNarrativeRoute = RuntimeNarrativeRouteImport.update({
  id: '/runtime/narrative',
  path: '/runtime/narrative',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleIdRoute = RuleIdRouteImport.update({
  id: '/rule/$id',
  path: '/rule/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternIdRoute = PatternIdRouteImport.update({
  id: '/pattern/$id',
  path: '/pattern/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationIdRoute = ObservationIdRouteImport.update({
  id: '/observation/$id',
  path: '/observation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrativeIdRoute = NarrativeIdRouteImport.update({
  id: '/narrative/$id',
  path: '/narrative/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePacksValidateRoute = KnowledgePacksValidateRouteImport.update({
  id: '/knowledge-packs/validate',
  path: '/knowledge-packs/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePacksReloadRoute = KnowledgePacksReloadRouteImport.update({
  id: '/knowledge-packs/reload',
  path: '/knowledge-packs/reload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsRoute = ApiAssessmentsRouteImport.update({
  id: '/api/assessments',
  path: '/api/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePackIdIndexRoute = KnowledgePackIdIndexRouteImport.update({
  id: '/knowledge-pack/$id/',
  path: '/knowledge-pack/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSignalsIndexRoute = InternalSignalsIndexRouteImport.update({
  id: '/internal/signals/',
  path: '/internal/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalScoresIndexRoute = InternalScoresIndexRouteImport.update({
  id: '/internal/scores/',
  path: '/internal/scores/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRulesIndexRoute = InternalRulesIndexRouteImport.update({
  id: '/internal/rules/',
  path: '/internal/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPatternsIndexRoute = InternalPatternsIndexRouteImport.update({
  id: '/internal/patterns/',
  path: '/internal/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalObservationsIndexRoute =
  InternalObservationsIndexRouteImport.update({
    id: '/internal/observations/',
    path: '/internal/observations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalNarrativesIndexRoute = InternalNarrativesIndexRouteImport.update({
  id: '/internal/narratives/',
  path: '/internal/narratives/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalKnowledgePacksIndexRoute =
  InternalKnowledgePacksIndexRouteImport.update({
    id: '/internal/knowledge-packs/',
    path: '/internal/knowledge-packs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentIdIndexRoute = AssessmentIdIndexRouteImport.update({
  id: '/assessment/$id/',
  path: '/assessment/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdDownloadRoute = ReportIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ReportIdRoute,
} as any)
const KnowledgePackIdVersionsRoute = KnowledgePackIdVersionsRouteImport.update({
  id: '/knowledge-pack/$id/versions',
  path: '/knowledge-pack/$id/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePackIdActivateRoute = KnowledgePackIdActivateRouteImport.update({
  id: '/knowledge-pack/$id/activate',
  path: '/knowledge-pack/$id/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSignalsIdRoute = InternalSignalsIdRouteImport.update({
  id: '/internal/signals/$id',
  path: '/internal/signals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalScoresIdRoute = InternalScoresIdRouteImport.update({
  id: '/internal/scores/$id',
  path: '/internal/scores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRulesIdRoute = InternalRulesIdRouteImport.update({
  id: '/internal/rules/$id',
  path: '/internal/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPatternsIdRoute = InternalPatternsIdRouteImport.update({
  id: '/internal/patterns/$id',
  path: '/internal/patterns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalObservationsIdRoute = InternalObservationsIdRouteImport.update({
  id: '/internal/observations/$id',
  path: '/internal/observations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalNarrativesIdRoute = InternalNarrativesIdRouteImport.update({
  id: '/internal/narratives/$id',
  path: '/internal/narratives/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalKnowledgePacksIdRoute =
  InternalKnowledgePacksIdRouteImport.update({
    id: '/internal/knowledge-packs/$id',
    path: '/internal/knowledge-packs/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentIdSummaryRoute = AssessmentIdSummaryRouteImport.update({
  id: '/assessment/$id/summary',
  path: '/assessment/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdSignalsRoute = AssessmentIdSignalsRouteImport.update({
  id: '/assessment/$id/signals',
  path: '/assessment/$id/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdScoresRoute = AssessmentIdScoresRouteImport.update({
  id: '/assessment/$id/scores',
  path: '/assessment/$id/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdRulesRoute = AssessmentIdRulesRouteImport.update({
  id: '/assessment/$id/rules',
  path: '/assessment/$id/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdResultsRoute = AssessmentIdResultsRouteImport.update({
  id: '/assessment/$id/results',
  path: '/assessment/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdReportsRoute = AssessmentIdReportsRouteImport.update({
  id: '/assessment/$id/reports',
  path: '/assessment/$id/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdProcessingRoute = AssessmentIdProcessingRouteImport.update({
  id: '/assessment/$id/processing',
  path: '/assessment/$id/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdPatternsRoute = AssessmentIdPatternsRouteImport.update({
  id: '/assessment/$id/patterns',
  path: '/assessment/$id/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdObservationsRoute =
  AssessmentIdObservationsRouteImport.update({
    id: '/assessment/$id/observations',
    path: '/assessment/$id/observations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentIdNarrativeRoute = AssessmentIdNarrativeRouteImport.update({
  id: '/assessment/$id/narrative',
  path: '/assessment/$id/narrative',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdDashboardRoute = AssessmentIdDashboardRouteImport.update({
  id: '/assessment/$id/dashboard',
  path: '/assessment/$id/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsIdRoute = ApiAssessmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAssessmentsRoute,
} as any)
const AssessmentIdExportFormatRoute =
  AssessmentIdExportFormatRouteImport.update({
    id: '/assessment/$id/export/$format',
    path: '/assessment/$id/export/$format',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAssessmentsIdSubmitRoute = ApiAssessmentsIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdStatusRoute = ApiAssessmentsIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdRetryRoute = ApiAssessmentsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdResultsRoute = ApiAssessmentsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdAdvanceRoute = ApiAssessmentsIdAdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRoute
  '/knowledge-packs/reload': typeof KnowledgePacksReloadRoute
  '/knowledge-packs/validate': typeof KnowledgePacksValidateRoute
  '/narrative/$id': typeof NarrativeIdRoute
  '/observation/$id': typeof ObservationIdRoute
  '/pattern/$id': typeof PatternIdRoute
  '/report/$id': typeof ReportIdRouteWithChildren
  '/rule/$id': typeof RuleIdRoute
  '/runtime/narrative': typeof RuntimeNarrativeRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/patterns': typeof RuntimePatternsRoute
  '/runtime/rules': typeof RuntimeRulesRoute
  '/runtime/scores': typeof RuntimeScoresRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/score/$id': typeof ScoreIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/knowledge-packs/': typeof KnowledgePacksIndexRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/dashboard': typeof AssessmentIdDashboardRoute
  '/assessment/$id/narrative': typeof AssessmentIdNarrativeRoute
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/patterns': typeof AssessmentIdPatternsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/reports': typeof AssessmentIdReportsRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/rules': typeof AssessmentIdRulesRoute
  '/assessment/$id/scores': typeof AssessmentIdScoresRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/assessment/$id/summary': typeof AssessmentIdSummaryRoute
  '/internal/knowledge-packs/$id': typeof InternalKnowledgePacksIdRoute
  '/internal/narratives/$id': typeof InternalNarrativesIdRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/internal/patterns/$id': typeof InternalPatternsIdRoute
  '/internal/rules/$id': typeof InternalRulesIdRoute
  '/internal/scores/$id': typeof InternalScoresIdRoute
  '/internal/signals/$id': typeof InternalSignalsIdRoute
  '/knowledge-pack/$id/activate': typeof KnowledgePackIdActivateRoute
  '/knowledge-pack/$id/versions': typeof KnowledgePackIdVersionsRoute
  '/report/$id/download': typeof ReportIdDownloadRoute
  '/assessment/$id/': typeof AssessmentIdIndexRoute
  '/internal/knowledge-packs/': typeof InternalKnowledgePacksIndexRoute
  '/internal/narratives/': typeof InternalNarrativesIndexRoute
  '/internal/observations/': typeof InternalObservationsIndexRoute
  '/internal/patterns/': typeof InternalPatternsIndexRoute
  '/internal/rules/': typeof InternalRulesIndexRoute
  '/internal/scores/': typeof InternalScoresIndexRoute
  '/internal/signals/': typeof InternalSignalsIndexRoute
  '/knowledge-pack/$id/': typeof KnowledgePackIdIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
  '/assessment/$id/export/$format': typeof AssessmentIdExportFormatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRoute
  '/knowledge-packs/reload': typeof KnowledgePacksReloadRoute
  '/knowledge-packs/validate': typeof KnowledgePacksValidateRoute
  '/narrative/$id': typeof NarrativeIdRoute
  '/observation/$id': typeof ObservationIdRoute
  '/pattern/$id': typeof PatternIdRoute
  '/report/$id': typeof ReportIdRouteWithChildren
  '/rule/$id': typeof RuleIdRoute
  '/runtime/narrative': typeof RuntimeNarrativeRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/patterns': typeof RuntimePatternsRoute
  '/runtime/rules': typeof RuntimeRulesRoute
  '/runtime/scores': typeof RuntimeScoresRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/score/$id': typeof ScoreIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/knowledge-packs': typeof KnowledgePacksIndexRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/dashboard': typeof AssessmentIdDashboardRoute
  '/assessment/$id/narrative': typeof AssessmentIdNarrativeRoute
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/patterns': typeof AssessmentIdPatternsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/reports': typeof AssessmentIdReportsRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/rules': typeof AssessmentIdRulesRoute
  '/assessment/$id/scores': typeof AssessmentIdScoresRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/assessment/$id/summary': typeof AssessmentIdSummaryRoute
  '/internal/knowledge-packs/$id': typeof InternalKnowledgePacksIdRoute
  '/internal/narratives/$id': typeof InternalNarrativesIdRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/internal/patterns/$id': typeof InternalPatternsIdRoute
  '/internal/rules/$id': typeof InternalRulesIdRoute
  '/internal/scores/$id': typeof InternalScoresIdRoute
  '/internal/signals/$id': typeof InternalSignalsIdRoute
  '/knowledge-pack/$id/activate': typeof KnowledgePackIdActivateRoute
  '/knowledge-pack/$id/versions': typeof KnowledgePackIdVersionsRoute
  '/report/$id/download': typeof ReportIdDownloadRoute
  '/assessment/$id': typeof AssessmentIdIndexRoute
  '/internal/knowledge-packs': typeof InternalKnowledgePacksIndexRoute
  '/internal/narratives': typeof InternalNarrativesIndexRoute
  '/internal/observations': typeof InternalObservationsIndexRoute
  '/internal/patterns': typeof InternalPatternsIndexRoute
  '/internal/rules': typeof InternalRulesIndexRoute
  '/internal/scores': typeof InternalScoresIndexRoute
  '/internal/signals': typeof InternalSignalsIndexRoute
  '/knowledge-pack/$id': typeof KnowledgePackIdIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
  '/assessment/$id/export/$format': typeof AssessmentIdExportFormatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRoute
  '/knowledge-packs/reload': typeof KnowledgePacksReloadRoute
  '/knowledge-packs/validate': typeof KnowledgePacksValidateRoute
  '/narrative/$id': typeof NarrativeIdRoute
  '/observation/$id': typeof ObservationIdRoute
  '/pattern/$id': typeof PatternIdRoute
  '/report/$id': typeof ReportIdRouteWithChildren
  '/rule/$id': typeof RuleIdRoute
  '/runtime/narrative': typeof RuntimeNarrativeRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/patterns': typeof RuntimePatternsRoute
  '/runtime/rules': typeof RuntimeRulesRoute
  '/runtime/scores': typeof RuntimeScoresRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/score/$id': typeof ScoreIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/knowledge-packs/': typeof KnowledgePacksIndexRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/dashboard': typeof AssessmentIdDashboardRoute
  '/assessment/$id/narrative': typeof AssessmentIdNarrativeRoute
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/patterns': typeof AssessmentIdPatternsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/reports': typeof AssessmentIdReportsRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/rules': typeof AssessmentIdRulesRoute
  '/assessment/$id/scores': typeof AssessmentIdScoresRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/assessment/$id/summary': typeof AssessmentIdSummaryRoute
  '/internal/knowledge-packs/$id': typeof InternalKnowledgePacksIdRoute
  '/internal/narratives/$id': typeof InternalNarrativesIdRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/internal/patterns/$id': typeof InternalPatternsIdRoute
  '/internal/rules/$id': typeof InternalRulesIdRoute
  '/internal/scores/$id': typeof InternalScoresIdRoute
  '/internal/signals/$id': typeof InternalSignalsIdRoute
  '/knowledge-pack/$id/activate': typeof KnowledgePackIdActivateRoute
  '/knowledge-pack/$id/versions': typeof KnowledgePackIdVersionsRoute
  '/report/$id/download': typeof ReportIdDownloadRoute
  '/assessment/$id/': typeof AssessmentIdIndexRoute
  '/internal/knowledge-packs/': typeof InternalKnowledgePacksIndexRoute
  '/internal/narratives/': typeof InternalNarrativesIndexRoute
  '/internal/observations/': typeof InternalObservationsIndexRoute
  '/internal/patterns/': typeof InternalPatternsIndexRoute
  '/internal/rules/': typeof InternalRulesIndexRoute
  '/internal/scores/': typeof InternalScoresIndexRoute
  '/internal/signals/': typeof InternalSignalsIndexRoute
  '/knowledge-pack/$id/': typeof KnowledgePackIdIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
  '/assessment/$id/export/$format': typeof AssessmentIdExportFormatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/assessments'
    | '/dashboard/$id'
    | '/knowledge-packs/reload'
    | '/knowledge-packs/validate'
    | '/narrative/$id'
    | '/observation/$id'
    | '/pattern/$id'
    | '/report/$id'
    | '/rule/$id'
    | '/runtime/narrative'
    | '/runtime/observations'
    | '/runtime/patterns'
    | '/runtime/rules'
    | '/runtime/scores'
    | '/runtime/signals'
    | '/score/$id'
    | '/signal/$id'
    | '/knowledge-packs/'
    | '/api/assessments/$id'
    | '/assessment/$id/dashboard'
    | '/assessment/$id/narrative'
    | '/assessment/$id/observations'
    | '/assessment/$id/patterns'
    | '/assessment/$id/processing'
    | '/assessment/$id/reports'
    | '/assessment/$id/results'
    | '/assessment/$id/rules'
    | '/assessment/$id/scores'
    | '/assessment/$id/signals'
    | '/assessment/$id/summary'
    | '/internal/knowledge-packs/$id'
    | '/internal/narratives/$id'
    | '/internal/observations/$id'
    | '/internal/patterns/$id'
    | '/internal/rules/$id'
    | '/internal/scores/$id'
    | '/internal/signals/$id'
    | '/knowledge-pack/$id/activate'
    | '/knowledge-pack/$id/versions'
    | '/report/$id/download'
    | '/assessment/$id/'
    | '/internal/knowledge-packs/'
    | '/internal/narratives/'
    | '/internal/observations/'
    | '/internal/patterns/'
    | '/internal/rules/'
    | '/internal/scores/'
    | '/internal/signals/'
    | '/knowledge-pack/$id/'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
    | '/assessment/$id/export/$format'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assessments'
    | '/dashboard/$id'
    | '/knowledge-packs/reload'
    | '/knowledge-packs/validate'
    | '/narrative/$id'
    | '/observation/$id'
    | '/pattern/$id'
    | '/report/$id'
    | '/rule/$id'
    | '/runtime/narrative'
    | '/runtime/observations'
    | '/runtime/patterns'
    | '/runtime/rules'
    | '/runtime/scores'
    | '/runtime/signals'
    | '/score/$id'
    | '/signal/$id'
    | '/knowledge-packs'
    | '/api/assessments/$id'
    | '/assessment/$id/dashboard'
    | '/assessment/$id/narrative'
    | '/assessment/$id/observations'
    | '/assessment/$id/patterns'
    | '/assessment/$id/processing'
    | '/assessment/$id/reports'
    | '/assessment/$id/results'
    | '/assessment/$id/rules'
    | '/assessment/$id/scores'
    | '/assessment/$id/signals'
    | '/assessment/$id/summary'
    | '/internal/knowledge-packs/$id'
    | '/internal/narratives/$id'
    | '/internal/observations/$id'
    | '/internal/patterns/$id'
    | '/internal/rules/$id'
    | '/internal/scores/$id'
    | '/internal/signals/$id'
    | '/knowledge-pack/$id/activate'
    | '/knowledge-pack/$id/versions'
    | '/report/$id/download'
    | '/assessment/$id'
    | '/internal/knowledge-packs'
    | '/internal/narratives'
    | '/internal/observations'
    | '/internal/patterns'
    | '/internal/rules'
    | '/internal/scores'
    | '/internal/signals'
    | '/knowledge-pack/$id'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
    | '/assessment/$id/export/$format'
  id:
    | '__root__'
    | '/'
    | '/api/assessments'
    | '/dashboard/$id'
    | '/knowledge-packs/reload'
    | '/knowledge-packs/validate'
    | '/narrative/$id'
    | '/observation/$id'
    | '/pattern/$id'
    | '/report/$id'
    | '/rule/$id'
    | '/runtime/narrative'
    | '/runtime/observations'
    | '/runtime/patterns'
    | '/runtime/rules'
    | '/runtime/scores'
    | '/runtime/signals'
    | '/score/$id'
    | '/signal/$id'
    | '/knowledge-packs/'
    | '/api/assessments/$id'
    | '/assessment/$id/dashboard'
    | '/assessment/$id/narrative'
    | '/assessment/$id/observations'
    | '/assessment/$id/patterns'
    | '/assessment/$id/processing'
    | '/assessment/$id/reports'
    | '/assessment/$id/results'
    | '/assessment/$id/rules'
    | '/assessment/$id/scores'
    | '/assessment/$id/signals'
    | '/assessment/$id/summary'
    | '/internal/knowledge-packs/$id'
    | '/internal/narratives/$id'
    | '/internal/observations/$id'
    | '/internal/patterns/$id'
    | '/internal/rules/$id'
    | '/internal/scores/$id'
    | '/internal/signals/$id'
    | '/knowledge-pack/$id/activate'
    | '/knowledge-pack/$id/versions'
    | '/report/$id/download'
    | '/assessment/$id/'
    | '/internal/knowledge-packs/'
    | '/internal/narratives/'
    | '/internal/observations/'
    | '/internal/patterns/'
    | '/internal/rules/'
    | '/internal/scores/'
    | '/internal/signals/'
    | '/knowledge-pack/$id/'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
    | '/assessment/$id/export/$format'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssessmentsRoute: typeof ApiAssessmentsRouteWithChildren
  DashboardIdRoute: typeof DashboardIdRoute
  KnowledgePacksReloadRoute: typeof KnowledgePacksReloadRoute
  KnowledgePacksValidateRoute: typeof KnowledgePacksValidateRoute
  NarrativeIdRoute: typeof NarrativeIdRoute
  ObservationIdRoute: typeof ObservationIdRoute
  PatternIdRoute: typeof PatternIdRoute
  ReportIdRoute: typeof ReportIdRouteWithChildren
  RuleIdRoute: typeof RuleIdRoute
  RuntimeNarrativeRoute: typeof RuntimeNarrativeRoute
  RuntimeObservationsRoute: typeof RuntimeObservationsRoute
  RuntimePatternsRoute: typeof RuntimePatternsRoute
  RuntimeRulesRoute: typeof RuntimeRulesRoute
  RuntimeScoresRoute: typeof RuntimeScoresRoute
  RuntimeSignalsRoute: typeof RuntimeSignalsRoute
  ScoreIdRoute: typeof ScoreIdRoute
  SignalIdRoute: typeof SignalIdRoute
  KnowledgePacksIndexRoute: typeof KnowledgePacksIndexRoute
  AssessmentIdDashboardRoute: typeof AssessmentIdDashboardRoute
  AssessmentIdNarrativeRoute: typeof AssessmentIdNarrativeRoute
  AssessmentIdObservationsRoute: typeof AssessmentIdObservationsRoute
  AssessmentIdPatternsRoute: typeof AssessmentIdPatternsRoute
  AssessmentIdProcessingRoute: typeof AssessmentIdProcessingRoute
  AssessmentIdReportsRoute: typeof AssessmentIdReportsRoute
  AssessmentIdResultsRoute: typeof AssessmentIdResultsRoute
  AssessmentIdRulesRoute: typeof AssessmentIdRulesRoute
  AssessmentIdScoresRoute: typeof AssessmentIdScoresRoute
  AssessmentIdSignalsRoute: typeof AssessmentIdSignalsRoute
  AssessmentIdSummaryRoute: typeof AssessmentIdSummaryRoute
  InternalKnowledgePacksIdRoute: typeof InternalKnowledgePacksIdRoute
  InternalNarrativesIdRoute: typeof InternalNarrativesIdRoute
  InternalObservationsIdRoute: typeof InternalObservationsIdRoute
  InternalPatternsIdRoute: typeof InternalPatternsIdRoute
  InternalRulesIdRoute: typeof InternalRulesIdRoute
  InternalScoresIdRoute: typeof InternalScoresIdRoute
  InternalSignalsIdRoute: typeof InternalSignalsIdRoute
  KnowledgePackIdActivateRoute: typeof KnowledgePackIdActivateRoute
  KnowledgePackIdVersionsRoute: typeof KnowledgePackIdVersionsRoute
  AssessmentIdIndexRoute: typeof AssessmentIdIndexRoute
  InternalKnowledgePacksIndexRoute: typeof InternalKnowledgePacksIndexRoute
  InternalNarrativesIndexRoute: typeof InternalNarrativesIndexRoute
  InternalObservationsIndexRoute: typeof InternalObservationsIndexRoute
  InternalPatternsIndexRoute: typeof InternalPatternsIndexRoute
  InternalRulesIndexRoute: typeof InternalRulesIndexRoute
  InternalScoresIndexRoute: typeof InternalScoresIndexRoute
  InternalSignalsIndexRoute: typeof InternalSignalsIndexRoute
  KnowledgePackIdIndexRoute: typeof KnowledgePackIdIndexRoute
  AssessmentIdExportFormatRoute: typeof AssessmentIdExportFormatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-packs/': {
      id: '/knowledge-packs/'
      path: '/knowledge-packs'
      fullPath: '/knowledge-packs/'
      preLoaderRoute: typeof KnowledgePacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal/$id': {
      id: '/signal/$id'
      path: '/signal/$id'
      fullPath: '/signal/$id'
      preLoaderRoute: typeof SignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score/$id': {
      id: '/score/$id'
      path: '/score/$id'
      fullPath: '/score/$id'
      preLoaderRoute: typeof ScoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/signals': {
      id: '/runtime/signals'
      path: '/runtime/signals'
      fullPath: '/runtime/signals'
      preLoaderRoute: typeof RuntimeSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/scores': {
      id: '/runtime/scores'
      path: '/runtime/scores'
      fullPath: '/runtime/scores'
      preLoaderRoute: typeof RuntimeScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/rules': {
      id: '/runtime/rules'
      path: '/runtime/rules'
      fullPath: '/runtime/rules'
      preLoaderRoute: typeof RuntimeRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/patterns': {
      id: '/runtime/patterns'
      path: '/runtime/patterns'
      fullPath: '/runtime/patterns'
      preLoaderRoute: typeof RuntimePatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/observations': {
      id: '/runtime/observations'
      path: '/runtime/observations'
      fullPath: '/runtime/observations'
      preLoaderRoute: typeof RuntimeObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/narrative': {
      id: '/runtime/narrative'
      path: '/runtime/narrative'
      fullPath: '/runtime/narrative'
      preLoaderRoute: typeof RuntimeNarrativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule/$id': {
      id: '/rule/$id'
      path: '/rule/$id'
      fullPath: '/rule/$id'
      preLoaderRoute: typeof RuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/$id': {
      id: '/pattern/$id'
      path: '/pattern/$id'
      fullPath: '/pattern/$id'
      preLoaderRoute: typeof PatternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observation/$id': {
      id: '/observation/$id'
      path: '/observation/$id'
      fullPath: '/observation/$id'
      preLoaderRoute: typeof ObservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narrative/$id': {
      id: '/narrative/$id'
      path: '/narrative/$id'
      fullPath: '/narrative/$id'
      preLoaderRoute: typeof NarrativeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-packs/validate': {
      id: '/knowledge-packs/validate'
      path: '/knowledge-packs/validate'
      fullPath: '/knowledge-packs/validate'
      preLoaderRoute: typeof KnowledgePacksValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-packs/reload': {
      id: '/knowledge-packs/reload'
      path: '/knowledge-packs/reload'
      fullPath: '/knowledge-packs/reload'
      preLoaderRoute: typeof KnowledgePacksReloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments': {
      id: '/api/assessments'
      path: '/api/assessments'
      fullPath: '/api/assessments'
      preLoaderRoute: typeof ApiAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-pack/$id/': {
      id: '/knowledge-pack/$id/'
      path: '/knowledge-pack/$id'
      fullPath: '/knowledge-pack/$id/'
      preLoaderRoute: typeof KnowledgePackIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/signals/': {
      id: '/internal/signals/'
      path: '/internal/signals'
      fullPath: '/internal/signals/'
      preLoaderRoute: typeof InternalSignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/scores/': {
      id: '/internal/scores/'
      path: '/internal/scores'
      fullPath: '/internal/scores/'
      preLoaderRoute: typeof InternalScoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/rules/': {
      id: '/internal/rules/'
      path: '/internal/rules'
      fullPath: '/internal/rules/'
      preLoaderRoute: typeof InternalRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/patterns/': {
      id: '/internal/patterns/'
      path: '/internal/patterns'
      fullPath: '/internal/patterns/'
      preLoaderRoute: typeof InternalPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/observations/': {
      id: '/internal/observations/'
      path: '/internal/observations'
      fullPath: '/internal/observations/'
      preLoaderRoute: typeof InternalObservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/narratives/': {
      id: '/internal/narratives/'
      path: '/internal/narratives'
      fullPath: '/internal/narratives/'
      preLoaderRoute: typeof InternalNarrativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/knowledge-packs/': {
      id: '/internal/knowledge-packs/'
      path: '/internal/knowledge-packs'
      fullPath: '/internal/knowledge-packs/'
      preLoaderRoute: typeof InternalKnowledgePacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/': {
      id: '/assessment/$id/'
      path: '/assessment/$id'
      fullPath: '/assessment/$id/'
      preLoaderRoute: typeof AssessmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id/download': {
      id: '/report/$id/download'
      path: '/download'
      fullPath: '/report/$id/download'
      preLoaderRoute: typeof ReportIdDownloadRouteImport
      parentRoute: typeof ReportIdRoute
    }
    '/knowledge-pack/$id/versions': {
      id: '/knowledge-pack/$id/versions'
      path: '/knowledge-pack/$id/versions'
      fullPath: '/knowledge-pack/$id/versions'
      preLoaderRoute: typeof KnowledgePackIdVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-pack/$id/activate': {
      id: '/knowledge-pack/$id/activate'
      path: '/knowledge-pack/$id/activate'
      fullPath: '/knowledge-pack/$id/activate'
      preLoaderRoute: typeof KnowledgePackIdActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/signals/$id': {
      id: '/internal/signals/$id'
      path: '/internal/signals/$id'
      fullPath: '/internal/signals/$id'
      preLoaderRoute: typeof InternalSignalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/scores/$id': {
      id: '/internal/scores/$id'
      path: '/internal/scores/$id'
      fullPath: '/internal/scores/$id'
      preLoaderRoute: typeof InternalScoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/rules/$id': {
      id: '/internal/rules/$id'
      path: '/internal/rules/$id'
      fullPath: '/internal/rules/$id'
      preLoaderRoute: typeof InternalRulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/patterns/$id': {
      id: '/internal/patterns/$id'
      path: '/internal/patterns/$id'
      fullPath: '/internal/patterns/$id'
      preLoaderRoute: typeof InternalPatternsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/observations/$id': {
      id: '/internal/observations/$id'
      path: '/internal/observations/$id'
      fullPath: '/internal/observations/$id'
      preLoaderRoute: typeof InternalObservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/narratives/$id': {
      id: '/internal/narratives/$id'
      path: '/internal/narratives/$id'
      fullPath: '/internal/narratives/$id'
      preLoaderRoute: typeof InternalNarrativesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/knowledge-packs/$id': {
      id: '/internal/knowledge-packs/$id'
      path: '/internal/knowledge-packs/$id'
      fullPath: '/internal/knowledge-packs/$id'
      preLoaderRoute: typeof InternalKnowledgePacksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/summary': {
      id: '/assessment/$id/summary'
      path: '/assessment/$id/summary'
      fullPath: '/assessment/$id/summary'
      preLoaderRoute: typeof AssessmentIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/signals': {
      id: '/assessment/$id/signals'
      path: '/assessment/$id/signals'
      fullPath: '/assessment/$id/signals'
      preLoaderRoute: typeof AssessmentIdSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/scores': {
      id: '/assessment/$id/scores'
      path: '/assessment/$id/scores'
      fullPath: '/assessment/$id/scores'
      preLoaderRoute: typeof AssessmentIdScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/rules': {
      id: '/assessment/$id/rules'
      path: '/assessment/$id/rules'
      fullPath: '/assessment/$id/rules'
      preLoaderRoute: typeof AssessmentIdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/results': {
      id: '/assessment/$id/results'
      path: '/assessment/$id/results'
      fullPath: '/assessment/$id/results'
      preLoaderRoute: typeof AssessmentIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/reports': {
      id: '/assessment/$id/reports'
      path: '/assessment/$id/reports'
      fullPath: '/assessment/$id/reports'
      preLoaderRoute: typeof AssessmentIdReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/processing': {
      id: '/assessment/$id/processing'
      path: '/assessment/$id/processing'
      fullPath: '/assessment/$id/processing'
      preLoaderRoute: typeof AssessmentIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/patterns': {
      id: '/assessment/$id/patterns'
      path: '/assessment/$id/patterns'
      fullPath: '/assessment/$id/patterns'
      preLoaderRoute: typeof AssessmentIdPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/observations': {
      id: '/assessment/$id/observations'
      path: '/assessment/$id/observations'
      fullPath: '/assessment/$id/observations'
      preLoaderRoute: typeof AssessmentIdObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/narrative': {
      id: '/assessment/$id/narrative'
      path: '/assessment/$id/narrative'
      fullPath: '/assessment/$id/narrative'
      preLoaderRoute: typeof AssessmentIdNarrativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/dashboard': {
      id: '/assessment/$id/dashboard'
      path: '/assessment/$id/dashboard'
      fullPath: '/assessment/$id/dashboard'
      preLoaderRoute: typeof AssessmentIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments/$id': {
      id: '/api/assessments/$id'
      path: '/$id'
      fullPath: '/api/assessments/$id'
      preLoaderRoute: typeof ApiAssessmentsIdRouteImport
      parentRoute: typeof ApiAssessmentsRoute
    }
    '/assessment/$id/export/$format': {
      id: '/assessment/$id/export/$format'
      path: '/assessment/$id/export/$format'
      fullPath: '/assessment/$id/export/$format'
      preLoaderRoute: typeof AssessmentIdExportFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments/$id/submit': {
      id: '/api/assessments/$id/submit'
      path: '/submit'
      fullPath: '/api/assessments/$id/submit'
      preLoaderRoute: typeof ApiAssessmentsIdSubmitRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/status': {
      id: '/api/assessments/$id/status'
      path: '/status'
      fullPath: '/api/assessments/$id/status'
      preLoaderRoute: typeof ApiAssessmentsIdStatusRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/retry': {
      id: '/api/assessments/$id/retry'
      path: '/retry'
      fullPath: '/api/assessments/$id/retry'
      preLoaderRoute: typeof ApiAssessmentsIdRetryRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/results': {
      id: '/api/assessments/$id/results'
      path: '/results'
      fullPath: '/api/assessments/$id/results'
      preLoaderRoute: typeof ApiAssessmentsIdResultsRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/advance': {
      id: '/api/assessments/$id/advance'
      path: '/advance'
      fullPath: '/api/assessments/$id/advance'
      preLoaderRoute: typeof ApiAssessmentsIdAdvanceRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
  }
}

interface ApiAssessmentsIdRouteChildren {
  ApiAssessmentsIdAdvanceRoute: typeof ApiAssessmentsIdAdvanceRoute
  ApiAssessmentsIdResultsRoute: typeof ApiAssessmentsIdResultsRoute
  ApiAssessmentsIdRetryRoute: typeof ApiAssessmentsIdRetryRoute
  ApiAssessmentsIdStatusRoute: typeof ApiAssessmentsIdStatusRoute
  ApiAssessmentsIdSubmitRoute: typeof ApiAssessmentsIdSubmitRoute
}

const ApiAssessmentsIdRouteChildren: ApiAssessmentsIdRouteChildren = {
  ApiAssessmentsIdAdvanceRoute: ApiAssessmentsIdAdvanceRoute,
  ApiAssessmentsIdResultsRoute: ApiAssessmentsIdResultsRoute,
  ApiAssessmentsIdRetryRoute: ApiAssessmentsIdRetryRoute,
  ApiAssessmentsIdStatusRoute: ApiAssessmentsIdStatusRoute,
  ApiAssessmentsIdSubmitRoute: ApiAssessmentsIdSubmitRoute,
}

const ApiAssessmentsIdRouteWithChildren =
  ApiAssessmentsIdRoute._addFileChildren(ApiAssessmentsIdRouteChildren)

interface ApiAssessmentsRouteChildren {
  ApiAssessmentsIdRoute: typeof ApiAssessmentsIdRouteWithChildren
}

const ApiAssessmentsRouteChildren: ApiAssessmentsRouteChildren = {
  ApiAssessmentsIdRoute: ApiAssessmentsIdRouteWithChildren,
}

const ApiAssessmentsRouteWithChildren = ApiAssessmentsRoute._addFileChildren(
  ApiAssessmentsRouteChildren,
)

interface ReportIdRouteChildren {
  ReportIdDownloadRoute: typeof ReportIdDownloadRoute
}

const ReportIdRouteChildren: ReportIdRouteChildren = {
  ReportIdDownloadRoute: ReportIdDownloadRoute,
}

const ReportIdRouteWithChildren = ReportIdRoute._addFileChildren(
  ReportIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssessmentsRoute: ApiAssessmentsRouteWithChildren,
  DashboardIdRoute: DashboardIdRoute,
  KnowledgePacksReloadRoute: KnowledgePacksReloadRoute,
  KnowledgePacksValidateRoute: KnowledgePacksValidateRoute,
  NarrativeIdRoute: NarrativeIdRoute,
  ObservationIdRoute: ObservationIdRoute,
  PatternIdRoute: PatternIdRoute,
  ReportIdRoute: ReportIdRouteWithChildren,
  RuleIdRoute: RuleIdRoute,
  RuntimeNarrativeRoute: RuntimeNarrativeRoute,
  RuntimeObservationsRoute: RuntimeObservationsRoute,
  RuntimePatternsRoute: RuntimePatternsRoute,
  RuntimeRulesRoute: RuntimeRulesRoute,
  RuntimeScoresRoute: RuntimeScoresRoute,
  RuntimeSignalsRoute: RuntimeSignalsRoute,
  ScoreIdRoute: ScoreIdRoute,
  SignalIdRoute: SignalIdRoute,
  KnowledgePacksIndexRoute: KnowledgePacksIndexRoute,
  AssessmentIdDashboardRoute: AssessmentIdDashboardRoute,
  AssessmentIdNarrativeRoute: AssessmentIdNarrativeRoute,
  AssessmentIdObservationsRoute: AssessmentIdObservationsRoute,
  AssessmentIdPatternsRoute: AssessmentIdPatternsRoute,
  AssessmentIdProcessingRoute: AssessmentIdProcessingRoute,
  AssessmentIdReportsRoute: AssessmentIdReportsRoute,
  AssessmentIdResultsRoute: AssessmentIdResultsRoute,
  AssessmentIdRulesRoute: AssessmentIdRulesRoute,
  AssessmentIdScoresRoute: AssessmentIdScoresRoute,
  AssessmentIdSignalsRoute: AssessmentIdSignalsRoute,
  AssessmentIdSummaryRoute: AssessmentIdSummaryRoute,
  InternalKnowledgePacksIdRoute: InternalKnowledgePacksIdRoute,
  InternalNarrativesIdRoute: InternalNarrativesIdRoute,
  InternalObservationsIdRoute: InternalObservationsIdRoute,
  InternalPatternsIdRoute: InternalPatternsIdRoute,
  InternalRulesIdRoute: InternalRulesIdRoute,
  InternalScoresIdRoute: InternalScoresIdRoute,
  InternalSignalsIdRoute: InternalSignalsIdRoute,
  KnowledgePackIdActivateRoute: KnowledgePackIdActivateRoute,
  KnowledgePackIdVersionsRoute: KnowledgePackIdVersionsRoute,
  AssessmentIdIndexRoute: AssessmentIdIndexRoute,
  InternalKnowledgePacksIndexRoute: InternalKnowledgePacksIndexRoute,
  InternalNarrativesIndexRoute: InternalNarrativesIndexRoute,
  InternalObservationsIndexRoute: InternalObservationsIndexRoute,
  InternalPatternsIndexRoute: InternalPatternsIndexRoute,
  InternalRulesIndexRoute: InternalRulesIndexRoute,
  InternalScoresIndexRoute: InternalScoresIndexRoute,
  InternalSignalsIndexRoute: InternalSignalsIndexRoute,
  KnowledgePackIdIndexRoute: KnowledgePackIdIndexRoute,
  AssessmentIdExportFormatRoute: AssessmentIdExportFormatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
