/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalIdRouteImport } from './routes/signal.$id'
import { Route as ScoreIdRouteImport } from './routes/score.$id'
import { Route as RuntimeSignalsRouteImport } from './routes/runtime.signals'
import { Route as RuntimeScoresRouteImport } from './routes/runtime.scores'
import { Route as RuntimeRulesRouteImport } from './routes/runtime.rules'
import { Route as RuntimePatternsRouteImport } from './routes/runtime.patterns'
import { Route as RuntimeObservationsRouteImport } from './routes/runtime.observations'
import { Route as RuntimeNarrativeRouteImport } from './routes/runtime.narrative'
import { Route as RuleIdRouteImport } from './routes/rule.$id'
import { Route as PatternIdRouteImport } from './routes/pattern.$id'
import { Route as ObservationIdRouteImport } from './routes/observation.$id'
import { Route as NarrativeIdRouteImport } from './routes/narrative.$id'
import { Route as ApiAssessmentsRouteImport } from './routes/api/assessments'
import { Route as InternalSignalsIndexRouteImport } from './routes/internal.signals.index'
import { Route as InternalScoresIndexRouteImport } from './routes/internal.scores.index'
import { Route as InternalRulesIndexRouteImport } from './routes/internal.rules.index'
import { Route as InternalPatternsIndexRouteImport } from './routes/internal.patterns.index'
import { Route as InternalObservationsIndexRouteImport } from './routes/internal.observations.index'
import { Route as InternalNarrativesIndexRouteImport } from './routes/internal.narratives.index'
import { Route as AssessmentIdIndexRouteImport } from './routes/assessment.$id.index'
import { Route as InternalSignalsIdRouteImport } from './routes/internal.signals.$id'
import { Route as InternalScoresIdRouteImport } from './routes/internal.scores.$id'
import { Route as InternalRulesIdRouteImport } from './routes/internal.rules.$id'
import { Route as InternalPatternsIdRouteImport } from './routes/internal.patterns.$id'
import { Route as InternalObservationsIdRouteImport } from './routes/internal.observations.$id'
import { Route as InternalNarrativesIdRouteImport } from './routes/internal.narratives.$id'
import { Route as AssessmentIdSummaryRouteImport } from './routes/assessment.$id.summary'
import { Route as AssessmentIdSignalsRouteImport } from './routes/assessment.$id.signals'
import { Route as AssessmentIdScoresRouteImport } from './routes/assessment.$id.scores'
import { Route as AssessmentIdRulesRouteImport } from './routes/assessment.$id.rules'
import { Route as AssessmentIdResultsRouteImport } from './routes/assessment.$id.results'
import { Route as AssessmentIdProcessingRouteImport } from './routes/assessment.$id.processing'
import { Route as AssessmentIdPatternsRouteImport } from './routes/assessment.$id.patterns'
import { Route as AssessmentIdObservationsRouteImport } from './routes/assessment.$id.observations'
import { Route as AssessmentIdNarrativeRouteImport } from './routes/assessment.$id.narrative'
import { Route as ApiAssessmentsIdRouteImport } from './routes/api/assessments.$id'
import { Route as ApiAssessmentsIdSubmitRouteImport } from './routes/api/assessments.$id.submit'
import { Route as ApiAssessmentsIdStatusRouteImport } from './routes/api/assessments.$id.status'
import { Route as ApiAssessmentsIdRetryRouteImport } from './routes/api/assessments.$id.retry'
import { Route as ApiAssessmentsIdResultsRouteImport } from './routes/api/assessments.$id.results'
import { Route as ApiAssessmentsIdAdvanceRouteImport } from './routes/api/assessments.$id.advance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalIdRoute = SignalIdRouteImport.update({
  id: '/signal/$id',
  path: '/signal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreIdRoute = ScoreIdRouteImport.update({
  id: '/score/$id',
  path: '/score/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeSignalsRoute = RuntimeSignalsRouteImport.update({
  id: '/runtime/signals',
  path: '/runtime/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeScoresRoute = RuntimeScoresRouteImport.update({
  id: '/runtime/scores',
  path: '/runtime/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRulesRoute = RuntimeRulesRouteImport.update({
  id: '/runtime/rules',
  path: '/runtime/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimePatternsRoute = RuntimePatternsRouteImport.update({
  id: '/runtime/patterns',
  path: '/runtime/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeObservationsRoute = RuntimeObservationsRouteImport.update({
  id: '/runtime/observations',
  path: '/runtime/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeNarrativeRoute = RuntimeNarrativeRouteImport.update({
  id: '/runtime/narrative',
  path: '/runtime/narrative',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleIdRoute = RuleIdRouteImport.update({
  id: '/rule/$id',
  path: '/rule/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternIdRoute = PatternIdRouteImport.update({
  id: '/pattern/$id',
  path: '/pattern/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationIdRoute = ObservationIdRouteImport.update({
  id: '/observation/$id',
  path: '/observation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrativeIdRoute = NarrativeIdRouteImport.update({
  id: '/narrative/$id',
  path: '/narrative/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsRoute = ApiAssessmentsRouteImport.update({
  id: '/api/assessments',
  path: '/api/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSignalsIndexRoute = InternalSignalsIndexRouteImport.update({
  id: '/internal/signals/',
  path: '/internal/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalScoresIndexRoute = InternalScoresIndexRouteImport.update({
  id: '/internal/scores/',
  path: '/internal/scores/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRulesIndexRoute = InternalRulesIndexRouteImport.update({
  id: '/internal/rules/',
  path: '/internal/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPatternsIndexRoute = InternalPatternsIndexRouteImport.update({
  id: '/internal/patterns/',
  path: '/internal/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalObservationsIndexRoute =
  InternalObservationsIndexRouteImport.update({
    id: '/internal/observations/',
    path: '/internal/observations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalNarrativesIndexRoute = InternalNarrativesIndexRouteImport.update({
  id: '/internal/narratives/',
  path: '/internal/narratives/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdIndexRoute = AssessmentIdIndexRouteImport.update({
  id: '/assessment/$id/',
  path: '/assessment/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSignalsIdRoute = InternalSignalsIdRouteImport.update({
  id: '/internal/signals/$id',
  path: '/internal/signals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalScoresIdRoute = InternalScoresIdRouteImport.update({
  id: '/internal/scores/$id',
  path: '/internal/scores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRulesIdRoute = InternalRulesIdRouteImport.update({
  id: '/internal/rules/$id',
  path: '/internal/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPatternsIdRoute = InternalPatternsIdRouteImport.update({
  id: '/internal/patterns/$id',
  path: '/internal/patterns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalObservationsIdRoute = InternalObservationsIdRouteImport.update({
  id: '/internal/observations/$id',
  path: '/internal/observations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalNarrativesIdRoute = InternalNarrativesIdRouteImport.update({
  id: '/internal/narratives/$id',
  path: '/internal/narratives/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdSummaryRoute = AssessmentIdSummaryRouteImport.update({
  id: '/assessment/$id/summary',
  path: '/assessment/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdSignalsRoute = AssessmentIdSignalsRouteImport.update({
  id: '/assessment/$id/signals',
  path: '/assessment/$id/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdScoresRoute = AssessmentIdScoresRouteImport.update({
  id: '/assessment/$id/scores',
  path: '/assessment/$id/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdRulesRoute = AssessmentIdRulesRouteImport.update({
  id: '/assessment/$id/rules',
  path: '/assessment/$id/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdResultsRoute = AssessmentIdResultsRouteImport.update({
  id: '/assessment/$id/results',
  path: '/assessment/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdProcessingRoute = AssessmentIdProcessingRouteImport.update({
  id: '/assessment/$id/processing',
  path: '/assessment/$id/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdPatternsRoute = AssessmentIdPatternsRouteImport.update({
  id: '/assessment/$id/patterns',
  path: '/assessment/$id/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdObservationsRoute =
  AssessmentIdObservationsRouteImport.update({
    id: '/assessment/$id/observations',
    path: '/assessment/$id/observations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentIdNarrativeRoute = AssessmentIdNarrativeRouteImport.update({
  id: '/assessment/$id/narrative',
  path: '/assessment/$id/narrative',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsIdRoute = ApiAssessmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAssessmentsRoute,
} as any)
const ApiAssessmentsIdSubmitRoute = ApiAssessmentsIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdStatusRoute = ApiAssessmentsIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdRetryRoute = ApiAssessmentsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdResultsRoute = ApiAssessmentsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdAdvanceRoute = ApiAssessmentsIdAdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/narrative/$id': typeof NarrativeIdRoute
  '/observation/$id': typeof ObservationIdRoute
  '/pattern/$id': typeof PatternIdRoute
  '/rule/$id': typeof RuleIdRoute
  '/runtime/narrative': typeof RuntimeNarrativeRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/patterns': typeof RuntimePatternsRoute
  '/runtime/rules': typeof RuntimeRulesRoute
  '/runtime/scores': typeof RuntimeScoresRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/score/$id': typeof ScoreIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/narrative': typeof AssessmentIdNarrativeRoute
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/patterns': typeof AssessmentIdPatternsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/rules': typeof AssessmentIdRulesRoute
  '/assessment/$id/scores': typeof AssessmentIdScoresRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/assessment/$id/summary': typeof AssessmentIdSummaryRoute
  '/internal/narratives/$id': typeof InternalNarrativesIdRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/internal/patterns/$id': typeof InternalPatternsIdRoute
  '/internal/rules/$id': typeof InternalRulesIdRoute
  '/internal/scores/$id': typeof InternalScoresIdRoute
  '/internal/signals/$id': typeof InternalSignalsIdRoute
  '/assessment/$id/': typeof AssessmentIdIndexRoute
  '/internal/narratives/': typeof InternalNarrativesIndexRoute
  '/internal/observations/': typeof InternalObservationsIndexRoute
  '/internal/patterns/': typeof InternalPatternsIndexRoute
  '/internal/rules/': typeof InternalRulesIndexRoute
  '/internal/scores/': typeof InternalScoresIndexRoute
  '/internal/signals/': typeof InternalSignalsIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/narrative/$id': typeof NarrativeIdRoute
  '/observation/$id': typeof ObservationIdRoute
  '/pattern/$id': typeof PatternIdRoute
  '/rule/$id': typeof RuleIdRoute
  '/runtime/narrative': typeof RuntimeNarrativeRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/patterns': typeof RuntimePatternsRoute
  '/runtime/rules': typeof RuntimeRulesRoute
  '/runtime/scores': typeof RuntimeScoresRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/score/$id': typeof ScoreIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/narrative': typeof AssessmentIdNarrativeRoute
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/patterns': typeof AssessmentIdPatternsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/rules': typeof AssessmentIdRulesRoute
  '/assessment/$id/scores': typeof AssessmentIdScoresRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/assessment/$id/summary': typeof AssessmentIdSummaryRoute
  '/internal/narratives/$id': typeof InternalNarrativesIdRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/internal/patterns/$id': typeof InternalPatternsIdRoute
  '/internal/rules/$id': typeof InternalRulesIdRoute
  '/internal/scores/$id': typeof InternalScoresIdRoute
  '/internal/signals/$id': typeof InternalSignalsIdRoute
  '/assessment/$id': typeof AssessmentIdIndexRoute
  '/internal/narratives': typeof InternalNarrativesIndexRoute
  '/internal/observations': typeof InternalObservationsIndexRoute
  '/internal/patterns': typeof InternalPatternsIndexRoute
  '/internal/rules': typeof InternalRulesIndexRoute
  '/internal/scores': typeof InternalScoresIndexRoute
  '/internal/signals': typeof InternalSignalsIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/narrative/$id': typeof NarrativeIdRoute
  '/observation/$id': typeof ObservationIdRoute
  '/pattern/$id': typeof PatternIdRoute
  '/rule/$id': typeof RuleIdRoute
  '/runtime/narrative': typeof RuntimeNarrativeRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/patterns': typeof RuntimePatternsRoute
  '/runtime/rules': typeof RuntimeRulesRoute
  '/runtime/scores': typeof RuntimeScoresRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/score/$id': typeof ScoreIdRoute
  '/signal/$id': typeof SignalIdRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/narrative': typeof AssessmentIdNarrativeRoute
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/patterns': typeof AssessmentIdPatternsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/rules': typeof AssessmentIdRulesRoute
  '/assessment/$id/scores': typeof AssessmentIdScoresRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/assessment/$id/summary': typeof AssessmentIdSummaryRoute
  '/internal/narratives/$id': typeof InternalNarrativesIdRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/internal/patterns/$id': typeof InternalPatternsIdRoute
  '/internal/rules/$id': typeof InternalRulesIdRoute
  '/internal/scores/$id': typeof InternalScoresIdRoute
  '/internal/signals/$id': typeof InternalSignalsIdRoute
  '/assessment/$id/': typeof AssessmentIdIndexRoute
  '/internal/narratives/': typeof InternalNarrativesIndexRoute
  '/internal/observations/': typeof InternalObservationsIndexRoute
  '/internal/patterns/': typeof InternalPatternsIndexRoute
  '/internal/rules/': typeof InternalRulesIndexRoute
  '/internal/scores/': typeof InternalScoresIndexRoute
  '/internal/signals/': typeof InternalSignalsIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/assessments'
    | '/narrative/$id'
    | '/observation/$id'
    | '/pattern/$id'
    | '/rule/$id'
    | '/runtime/narrative'
    | '/runtime/observations'
    | '/runtime/patterns'
    | '/runtime/rules'
    | '/runtime/scores'
    | '/runtime/signals'
    | '/score/$id'
    | '/signal/$id'
    | '/api/assessments/$id'
    | '/assessment/$id/narrative'
    | '/assessment/$id/observations'
    | '/assessment/$id/patterns'
    | '/assessment/$id/processing'
    | '/assessment/$id/results'
    | '/assessment/$id/rules'
    | '/assessment/$id/scores'
    | '/assessment/$id/signals'
    | '/assessment/$id/summary'
    | '/internal/narratives/$id'
    | '/internal/observations/$id'
    | '/internal/patterns/$id'
    | '/internal/rules/$id'
    | '/internal/scores/$id'
    | '/internal/signals/$id'
    | '/assessment/$id/'
    | '/internal/narratives/'
    | '/internal/observations/'
    | '/internal/patterns/'
    | '/internal/rules/'
    | '/internal/scores/'
    | '/internal/signals/'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assessments'
    | '/narrative/$id'
    | '/observation/$id'
    | '/pattern/$id'
    | '/rule/$id'
    | '/runtime/narrative'
    | '/runtime/observations'
    | '/runtime/patterns'
    | '/runtime/rules'
    | '/runtime/scores'
    | '/runtime/signals'
    | '/score/$id'
    | '/signal/$id'
    | '/api/assessments/$id'
    | '/assessment/$id/narrative'
    | '/assessment/$id/observations'
    | '/assessment/$id/patterns'
    | '/assessment/$id/processing'
    | '/assessment/$id/results'
    | '/assessment/$id/rules'
    | '/assessment/$id/scores'
    | '/assessment/$id/signals'
    | '/assessment/$id/summary'
    | '/internal/narratives/$id'
    | '/internal/observations/$id'
    | '/internal/patterns/$id'
    | '/internal/rules/$id'
    | '/internal/scores/$id'
    | '/internal/signals/$id'
    | '/assessment/$id'
    | '/internal/narratives'
    | '/internal/observations'
    | '/internal/patterns'
    | '/internal/rules'
    | '/internal/scores'
    | '/internal/signals'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
  id:
    | '__root__'
    | '/'
    | '/api/assessments'
    | '/narrative/$id'
    | '/observation/$id'
    | '/pattern/$id'
    | '/rule/$id'
    | '/runtime/narrative'
    | '/runtime/observations'
    | '/runtime/patterns'
    | '/runtime/rules'
    | '/runtime/scores'
    | '/runtime/signals'
    | '/score/$id'
    | '/signal/$id'
    | '/api/assessments/$id'
    | '/assessment/$id/narrative'
    | '/assessment/$id/observations'
    | '/assessment/$id/patterns'
    | '/assessment/$id/processing'
    | '/assessment/$id/results'
    | '/assessment/$id/rules'
    | '/assessment/$id/scores'
    | '/assessment/$id/signals'
    | '/assessment/$id/summary'
    | '/internal/narratives/$id'
    | '/internal/observations/$id'
    | '/internal/patterns/$id'
    | '/internal/rules/$id'
    | '/internal/scores/$id'
    | '/internal/signals/$id'
    | '/assessment/$id/'
    | '/internal/narratives/'
    | '/internal/observations/'
    | '/internal/patterns/'
    | '/internal/rules/'
    | '/internal/scores/'
    | '/internal/signals/'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssessmentsRoute: typeof ApiAssessmentsRouteWithChildren
  NarrativeIdRoute: typeof NarrativeIdRoute
  ObservationIdRoute: typeof ObservationIdRoute
  PatternIdRoute: typeof PatternIdRoute
  RuleIdRoute: typeof RuleIdRoute
  RuntimeNarrativeRoute: typeof RuntimeNarrativeRoute
  RuntimeObservationsRoute: typeof RuntimeObservationsRoute
  RuntimePatternsRoute: typeof RuntimePatternsRoute
  RuntimeRulesRoute: typeof RuntimeRulesRoute
  RuntimeScoresRoute: typeof RuntimeScoresRoute
  RuntimeSignalsRoute: typeof RuntimeSignalsRoute
  ScoreIdRoute: typeof ScoreIdRoute
  SignalIdRoute: typeof SignalIdRoute
  AssessmentIdNarrativeRoute: typeof AssessmentIdNarrativeRoute
  AssessmentIdObservationsRoute: typeof AssessmentIdObservationsRoute
  AssessmentIdPatternsRoute: typeof AssessmentIdPatternsRoute
  AssessmentIdProcessingRoute: typeof AssessmentIdProcessingRoute
  AssessmentIdResultsRoute: typeof AssessmentIdResultsRoute
  AssessmentIdRulesRoute: typeof AssessmentIdRulesRoute
  AssessmentIdScoresRoute: typeof AssessmentIdScoresRoute
  AssessmentIdSignalsRoute: typeof AssessmentIdSignalsRoute
  AssessmentIdSummaryRoute: typeof AssessmentIdSummaryRoute
  InternalNarrativesIdRoute: typeof InternalNarrativesIdRoute
  InternalObservationsIdRoute: typeof InternalObservationsIdRoute
  InternalPatternsIdRoute: typeof InternalPatternsIdRoute
  InternalRulesIdRoute: typeof InternalRulesIdRoute
  InternalScoresIdRoute: typeof InternalScoresIdRoute
  InternalSignalsIdRoute: typeof InternalSignalsIdRoute
  AssessmentIdIndexRoute: typeof AssessmentIdIndexRoute
  InternalNarrativesIndexRoute: typeof InternalNarrativesIndexRoute
  InternalObservationsIndexRoute: typeof InternalObservationsIndexRoute
  InternalPatternsIndexRoute: typeof InternalPatternsIndexRoute
  InternalRulesIndexRoute: typeof InternalRulesIndexRoute
  InternalScoresIndexRoute: typeof InternalScoresIndexRoute
  InternalSignalsIndexRoute: typeof InternalSignalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal/$id': {
      id: '/signal/$id'
      path: '/signal/$id'
      fullPath: '/signal/$id'
      preLoaderRoute: typeof SignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score/$id': {
      id: '/score/$id'
      path: '/score/$id'
      fullPath: '/score/$id'
      preLoaderRoute: typeof ScoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/signals': {
      id: '/runtime/signals'
      path: '/runtime/signals'
      fullPath: '/runtime/signals'
      preLoaderRoute: typeof RuntimeSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/scores': {
      id: '/runtime/scores'
      path: '/runtime/scores'
      fullPath: '/runtime/scores'
      preLoaderRoute: typeof RuntimeScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/rules': {
      id: '/runtime/rules'
      path: '/runtime/rules'
      fullPath: '/runtime/rules'
      preLoaderRoute: typeof RuntimeRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/patterns': {
      id: '/runtime/patterns'
      path: '/runtime/patterns'
      fullPath: '/runtime/patterns'
      preLoaderRoute: typeof RuntimePatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/observations': {
      id: '/runtime/observations'
      path: '/runtime/observations'
      fullPath: '/runtime/observations'
      preLoaderRoute: typeof RuntimeObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/narrative': {
      id: '/runtime/narrative'
      path: '/runtime/narrative'
      fullPath: '/runtime/narrative'
      preLoaderRoute: typeof RuntimeNarrativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule/$id': {
      id: '/rule/$id'
      path: '/rule/$id'
      fullPath: '/rule/$id'
      preLoaderRoute: typeof RuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/$id': {
      id: '/pattern/$id'
      path: '/pattern/$id'
      fullPath: '/pattern/$id'
      preLoaderRoute: typeof PatternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observation/$id': {
      id: '/observation/$id'
      path: '/observation/$id'
      fullPath: '/observation/$id'
      preLoaderRoute: typeof ObservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narrative/$id': {
      id: '/narrative/$id'
      path: '/narrative/$id'
      fullPath: '/narrative/$id'
      preLoaderRoute: typeof NarrativeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments': {
      id: '/api/assessments'
      path: '/api/assessments'
      fullPath: '/api/assessments'
      preLoaderRoute: typeof ApiAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/signals/': {
      id: '/internal/signals/'
      path: '/internal/signals'
      fullPath: '/internal/signals/'
      preLoaderRoute: typeof InternalSignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/scores/': {
      id: '/internal/scores/'
      path: '/internal/scores'
      fullPath: '/internal/scores/'
      preLoaderRoute: typeof InternalScoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/rules/': {
      id: '/internal/rules/'
      path: '/internal/rules'
      fullPath: '/internal/rules/'
      preLoaderRoute: typeof InternalRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/patterns/': {
      id: '/internal/patterns/'
      path: '/internal/patterns'
      fullPath: '/internal/patterns/'
      preLoaderRoute: typeof InternalPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/observations/': {
      id: '/internal/observations/'
      path: '/internal/observations'
      fullPath: '/internal/observations/'
      preLoaderRoute: typeof InternalObservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/narratives/': {
      id: '/internal/narratives/'
      path: '/internal/narratives'
      fullPath: '/internal/narratives/'
      preLoaderRoute: typeof InternalNarrativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/': {
      id: '/assessment/$id/'
      path: '/assessment/$id'
      fullPath: '/assessment/$id/'
      preLoaderRoute: typeof AssessmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/signals/$id': {
      id: '/internal/signals/$id'
      path: '/internal/signals/$id'
      fullPath: '/internal/signals/$id'
      preLoaderRoute: typeof InternalSignalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/scores/$id': {
      id: '/internal/scores/$id'
      path: '/internal/scores/$id'
      fullPath: '/internal/scores/$id'
      preLoaderRoute: typeof InternalScoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/rules/$id': {
      id: '/internal/rules/$id'
      path: '/internal/rules/$id'
      fullPath: '/internal/rules/$id'
      preLoaderRoute: typeof InternalRulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/patterns/$id': {
      id: '/internal/patterns/$id'
      path: '/internal/patterns/$id'
      fullPath: '/internal/patterns/$id'
      preLoaderRoute: typeof InternalPatternsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/observations/$id': {
      id: '/internal/observations/$id'
      path: '/internal/observations/$id'
      fullPath: '/internal/observations/$id'
      preLoaderRoute: typeof InternalObservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/narratives/$id': {
      id: '/internal/narratives/$id'
      path: '/internal/narratives/$id'
      fullPath: '/internal/narratives/$id'
      preLoaderRoute: typeof InternalNarrativesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/summary': {
      id: '/assessment/$id/summary'
      path: '/assessment/$id/summary'
      fullPath: '/assessment/$id/summary'
      preLoaderRoute: typeof AssessmentIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/signals': {
      id: '/assessment/$id/signals'
      path: '/assessment/$id/signals'
      fullPath: '/assessment/$id/signals'
      preLoaderRoute: typeof AssessmentIdSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/scores': {
      id: '/assessment/$id/scores'
      path: '/assessment/$id/scores'
      fullPath: '/assessment/$id/scores'
      preLoaderRoute: typeof AssessmentIdScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/rules': {
      id: '/assessment/$id/rules'
      path: '/assessment/$id/rules'
      fullPath: '/assessment/$id/rules'
      preLoaderRoute: typeof AssessmentIdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/results': {
      id: '/assessment/$id/results'
      path: '/assessment/$id/results'
      fullPath: '/assessment/$id/results'
      preLoaderRoute: typeof AssessmentIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/processing': {
      id: '/assessment/$id/processing'
      path: '/assessment/$id/processing'
      fullPath: '/assessment/$id/processing'
      preLoaderRoute: typeof AssessmentIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/patterns': {
      id: '/assessment/$id/patterns'
      path: '/assessment/$id/patterns'
      fullPath: '/assessment/$id/patterns'
      preLoaderRoute: typeof AssessmentIdPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/observations': {
      id: '/assessment/$id/observations'
      path: '/assessment/$id/observations'
      fullPath: '/assessment/$id/observations'
      preLoaderRoute: typeof AssessmentIdObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/narrative': {
      id: '/assessment/$id/narrative'
      path: '/assessment/$id/narrative'
      fullPath: '/assessment/$id/narrative'
      preLoaderRoute: typeof AssessmentIdNarrativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments/$id': {
      id: '/api/assessments/$id'
      path: '/$id'
      fullPath: '/api/assessments/$id'
      preLoaderRoute: typeof ApiAssessmentsIdRouteImport
      parentRoute: typeof ApiAssessmentsRoute
    }
    '/api/assessments/$id/submit': {
      id: '/api/assessments/$id/submit'
      path: '/submit'
      fullPath: '/api/assessments/$id/submit'
      preLoaderRoute: typeof ApiAssessmentsIdSubmitRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/status': {
      id: '/api/assessments/$id/status'
      path: '/status'
      fullPath: '/api/assessments/$id/status'
      preLoaderRoute: typeof ApiAssessmentsIdStatusRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/retry': {
      id: '/api/assessments/$id/retry'
      path: '/retry'
      fullPath: '/api/assessments/$id/retry'
      preLoaderRoute: typeof ApiAssessmentsIdRetryRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/results': {
      id: '/api/assessments/$id/results'
      path: '/results'
      fullPath: '/api/assessments/$id/results'
      preLoaderRoute: typeof ApiAssessmentsIdResultsRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/advance': {
      id: '/api/assessments/$id/advance'
      path: '/advance'
      fullPath: '/api/assessments/$id/advance'
      preLoaderRoute: typeof ApiAssessmentsIdAdvanceRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
  }
}

interface ApiAssessmentsIdRouteChildren {
  ApiAssessmentsIdAdvanceRoute: typeof ApiAssessmentsIdAdvanceRoute
  ApiAssessmentsIdResultsRoute: typeof ApiAssessmentsIdResultsRoute
  ApiAssessmentsIdRetryRoute: typeof ApiAssessmentsIdRetryRoute
  ApiAssessmentsIdStatusRoute: typeof ApiAssessmentsIdStatusRoute
  ApiAssessmentsIdSubmitRoute: typeof ApiAssessmentsIdSubmitRoute
}

const ApiAssessmentsIdRouteChildren: ApiAssessmentsIdRouteChildren = {
  ApiAssessmentsIdAdvanceRoute: ApiAssessmentsIdAdvanceRoute,
  ApiAssessmentsIdResultsRoute: ApiAssessmentsIdResultsRoute,
  ApiAssessmentsIdRetryRoute: ApiAssessmentsIdRetryRoute,
  ApiAssessmentsIdStatusRoute: ApiAssessmentsIdStatusRoute,
  ApiAssessmentsIdSubmitRoute: ApiAssessmentsIdSubmitRoute,
}

const ApiAssessmentsIdRouteWithChildren =
  ApiAssessmentsIdRoute._addFileChildren(ApiAssessmentsIdRouteChildren)

interface ApiAssessmentsRouteChildren {
  ApiAssessmentsIdRoute: typeof ApiAssessmentsIdRouteWithChildren
}

const ApiAssessmentsRouteChildren: ApiAssessmentsRouteChildren = {
  ApiAssessmentsIdRoute: ApiAssessmentsIdRouteWithChildren,
}

const ApiAssessmentsRouteWithChildren = ApiAssessmentsRoute._addFileChildren(
  ApiAssessmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssessmentsRoute: ApiAssessmentsRouteWithChildren,
  NarrativeIdRoute: NarrativeIdRoute,
  ObservationIdRoute: ObservationIdRoute,
  PatternIdRoute: PatternIdRoute,
  RuleIdRoute: RuleIdRoute,
  RuntimeNarrativeRoute: RuntimeNarrativeRoute,
  RuntimeObservationsRoute: RuntimeObservationsRoute,
  RuntimePatternsRoute: RuntimePatternsRoute,
  RuntimeRulesRoute: RuntimeRulesRoute,
  RuntimeScoresRoute: RuntimeScoresRoute,
  RuntimeSignalsRoute: RuntimeSignalsRoute,
  ScoreIdRoute: ScoreIdRoute,
  SignalIdRoute: SignalIdRoute,
  AssessmentIdNarrativeRoute: AssessmentIdNarrativeRoute,
  AssessmentIdObservationsRoute: AssessmentIdObservationsRoute,
  AssessmentIdPatternsRoute: AssessmentIdPatternsRoute,
  AssessmentIdProcessingRoute: AssessmentIdProcessingRoute,
  AssessmentIdResultsRoute: AssessmentIdResultsRoute,
  AssessmentIdRulesRoute: AssessmentIdRulesRoute,
  AssessmentIdScoresRoute: AssessmentIdScoresRoute,
  AssessmentIdSignalsRoute: AssessmentIdSignalsRoute,
  AssessmentIdSummaryRoute: AssessmentIdSummaryRoute,
  InternalNarrativesIdRoute: InternalNarrativesIdRoute,
  InternalObservationsIdRoute: InternalObservationsIdRoute,
  InternalPatternsIdRoute: InternalPatternsIdRoute,
  InternalRulesIdRoute: InternalRulesIdRoute,
  InternalScoresIdRoute: InternalScoresIdRoute,
  InternalSignalsIdRoute: InternalSignalsIdRoute,
  AssessmentIdIndexRoute: AssessmentIdIndexRoute,
  InternalNarrativesIndexRoute: InternalNarrativesIndexRoute,
  InternalObservationsIndexRoute: InternalObservationsIndexRoute,
  InternalPatternsIndexRoute: InternalPatternsIndexRoute,
  InternalRulesIndexRoute: InternalRulesIndexRoute,
  InternalScoresIndexRoute: InternalScoresIndexRoute,
  InternalSignalsIndexRoute: InternalSignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
