/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalIdRouteImport } from './routes/signal.$id'
import { Route as RuntimeSignalsRouteImport } from './routes/runtime.signals'
import { Route as RuntimeObservationsRouteImport } from './routes/runtime.observations'
import { Route as ObservationIdRouteImport } from './routes/observation.$id'
import { Route as ApiAssessmentsRouteImport } from './routes/api/assessments'
import { Route as InternalObservationsIndexRouteImport } from './routes/internal.observations.index'
import { Route as AssessmentIdIndexRouteImport } from './routes/assessment.$id.index'
import { Route as InternalObservationsIdRouteImport } from './routes/internal.observations.$id'
import { Route as AssessmentIdSignalsRouteImport } from './routes/assessment.$id.signals'
import { Route as AssessmentIdResultsRouteImport } from './routes/assessment.$id.results'
import { Route as AssessmentIdProcessingRouteImport } from './routes/assessment.$id.processing'
import { Route as AssessmentIdObservationsRouteImport } from './routes/assessment.$id.observations'
import { Route as ApiAssessmentsIdRouteImport } from './routes/api/assessments.$id'
import { Route as ApiAssessmentsIdSubmitRouteImport } from './routes/api/assessments.$id.submit'
import { Route as ApiAssessmentsIdStatusRouteImport } from './routes/api/assessments.$id.status'
import { Route as ApiAssessmentsIdRetryRouteImport } from './routes/api/assessments.$id.retry'
import { Route as ApiAssessmentsIdResultsRouteImport } from './routes/api/assessments.$id.results'
import { Route as ApiAssessmentsIdAdvanceRouteImport } from './routes/api/assessments.$id.advance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalIdRoute = SignalIdRouteImport.update({
  id: '/signal/$id',
  path: '/signal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeSignalsRoute = RuntimeSignalsRouteImport.update({
  id: '/runtime/signals',
  path: '/runtime/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeObservationsRoute = RuntimeObservationsRouteImport.update({
  id: '/runtime/observations',
  path: '/runtime/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationIdRoute = ObservationIdRouteImport.update({
  id: '/observation/$id',
  path: '/observation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsRoute = ApiAssessmentsRouteImport.update({
  id: '/api/assessments',
  path: '/api/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalObservationsIndexRoute =
  InternalObservationsIndexRouteImport.update({
    id: '/internal/observations/',
    path: '/internal/observations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentIdIndexRoute = AssessmentIdIndexRouteImport.update({
  id: '/assessment/$id/',
  path: '/assessment/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalObservationsIdRoute = InternalObservationsIdRouteImport.update({
  id: '/internal/observations/$id',
  path: '/internal/observations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdSignalsRoute = AssessmentIdSignalsRouteImport.update({
  id: '/assessment/$id/signals',
  path: '/assessment/$id/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdResultsRoute = AssessmentIdResultsRouteImport.update({
  id: '/assessment/$id/results',
  path: '/assessment/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdProcessingRoute = AssessmentIdProcessingRouteImport.update({
  id: '/assessment/$id/processing',
  path: '/assessment/$id/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdObservationsRoute =
  AssessmentIdObservationsRouteImport.update({
    id: '/assessment/$id/observations',
    path: '/assessment/$id/observations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAssessmentsIdRoute = ApiAssessmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAssessmentsRoute,
} as any)
const ApiAssessmentsIdSubmitRoute = ApiAssessmentsIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdStatusRoute = ApiAssessmentsIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdRetryRoute = ApiAssessmentsIdRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdResultsRoute = ApiAssessmentsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)
const ApiAssessmentsIdAdvanceRoute = ApiAssessmentsIdAdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => ApiAssessmentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/observation/$id': typeof ObservationIdRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/signal/$id': typeof SignalIdRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/assessment/$id/': typeof AssessmentIdIndexRoute
  '/internal/observations/': typeof InternalObservationsIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/observation/$id': typeof ObservationIdRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/signal/$id': typeof SignalIdRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/assessment/$id': typeof AssessmentIdIndexRoute
  '/internal/observations': typeof InternalObservationsIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/observation/$id': typeof ObservationIdRoute
  '/runtime/observations': typeof RuntimeObservationsRoute
  '/runtime/signals': typeof RuntimeSignalsRoute
  '/signal/$id': typeof SignalIdRoute
  '/api/assessments/$id': typeof ApiAssessmentsIdRouteWithChildren
  '/assessment/$id/observations': typeof AssessmentIdObservationsRoute
  '/assessment/$id/processing': typeof AssessmentIdProcessingRoute
  '/assessment/$id/results': typeof AssessmentIdResultsRoute
  '/assessment/$id/signals': typeof AssessmentIdSignalsRoute
  '/internal/observations/$id': typeof InternalObservationsIdRoute
  '/assessment/$id/': typeof AssessmentIdIndexRoute
  '/internal/observations/': typeof InternalObservationsIndexRoute
  '/api/assessments/$id/advance': typeof ApiAssessmentsIdAdvanceRoute
  '/api/assessments/$id/results': typeof ApiAssessmentsIdResultsRoute
  '/api/assessments/$id/retry': typeof ApiAssessmentsIdRetryRoute
  '/api/assessments/$id/status': typeof ApiAssessmentsIdStatusRoute
  '/api/assessments/$id/submit': typeof ApiAssessmentsIdSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/assessments'
    | '/observation/$id'
    | '/runtime/observations'
    | '/runtime/signals'
    | '/signal/$id'
    | '/api/assessments/$id'
    | '/assessment/$id/observations'
    | '/assessment/$id/processing'
    | '/assessment/$id/results'
    | '/assessment/$id/signals'
    | '/internal/observations/$id'
    | '/assessment/$id/'
    | '/internal/observations/'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assessments'
    | '/observation/$id'
    | '/runtime/observations'
    | '/runtime/signals'
    | '/signal/$id'
    | '/api/assessments/$id'
    | '/assessment/$id/observations'
    | '/assessment/$id/processing'
    | '/assessment/$id/results'
    | '/assessment/$id/signals'
    | '/internal/observations/$id'
    | '/assessment/$id'
    | '/internal/observations'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
  id:
    | '__root__'
    | '/'
    | '/api/assessments'
    | '/observation/$id'
    | '/runtime/observations'
    | '/runtime/signals'
    | '/signal/$id'
    | '/api/assessments/$id'
    | '/assessment/$id/observations'
    | '/assessment/$id/processing'
    | '/assessment/$id/results'
    | '/assessment/$id/signals'
    | '/internal/observations/$id'
    | '/assessment/$id/'
    | '/internal/observations/'
    | '/api/assessments/$id/advance'
    | '/api/assessments/$id/results'
    | '/api/assessments/$id/retry'
    | '/api/assessments/$id/status'
    | '/api/assessments/$id/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssessmentsRoute: typeof ApiAssessmentsRouteWithChildren
  ObservationIdRoute: typeof ObservationIdRoute
  RuntimeObservationsRoute: typeof RuntimeObservationsRoute
  RuntimeSignalsRoute: typeof RuntimeSignalsRoute
  SignalIdRoute: typeof SignalIdRoute
  AssessmentIdObservationsRoute: typeof AssessmentIdObservationsRoute
  AssessmentIdProcessingRoute: typeof AssessmentIdProcessingRoute
  AssessmentIdResultsRoute: typeof AssessmentIdResultsRoute
  AssessmentIdSignalsRoute: typeof AssessmentIdSignalsRoute
  InternalObservationsIdRoute: typeof InternalObservationsIdRoute
  AssessmentIdIndexRoute: typeof AssessmentIdIndexRoute
  InternalObservationsIndexRoute: typeof InternalObservationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal/$id': {
      id: '/signal/$id'
      path: '/signal/$id'
      fullPath: '/signal/$id'
      preLoaderRoute: typeof SignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/signals': {
      id: '/runtime/signals'
      path: '/runtime/signals'
      fullPath: '/runtime/signals'
      preLoaderRoute: typeof RuntimeSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/observations': {
      id: '/runtime/observations'
      path: '/runtime/observations'
      fullPath: '/runtime/observations'
      preLoaderRoute: typeof RuntimeObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observation/$id': {
      id: '/observation/$id'
      path: '/observation/$id'
      fullPath: '/observation/$id'
      preLoaderRoute: typeof ObservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments': {
      id: '/api/assessments'
      path: '/api/assessments'
      fullPath: '/api/assessments'
      preLoaderRoute: typeof ApiAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/observations/': {
      id: '/internal/observations/'
      path: '/internal/observations'
      fullPath: '/internal/observations/'
      preLoaderRoute: typeof InternalObservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/': {
      id: '/assessment/$id/'
      path: '/assessment/$id'
      fullPath: '/assessment/$id/'
      preLoaderRoute: typeof AssessmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/observations/$id': {
      id: '/internal/observations/$id'
      path: '/internal/observations/$id'
      fullPath: '/internal/observations/$id'
      preLoaderRoute: typeof InternalObservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/signals': {
      id: '/assessment/$id/signals'
      path: '/assessment/$id/signals'
      fullPath: '/assessment/$id/signals'
      preLoaderRoute: typeof AssessmentIdSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/results': {
      id: '/assessment/$id/results'
      path: '/assessment/$id/results'
      fullPath: '/assessment/$id/results'
      preLoaderRoute: typeof AssessmentIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/processing': {
      id: '/assessment/$id/processing'
      path: '/assessment/$id/processing'
      fullPath: '/assessment/$id/processing'
      preLoaderRoute: typeof AssessmentIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id/observations': {
      id: '/assessment/$id/observations'
      path: '/assessment/$id/observations'
      fullPath: '/assessment/$id/observations'
      preLoaderRoute: typeof AssessmentIdObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments/$id': {
      id: '/api/assessments/$id'
      path: '/$id'
      fullPath: '/api/assessments/$id'
      preLoaderRoute: typeof ApiAssessmentsIdRouteImport
      parentRoute: typeof ApiAssessmentsRoute
    }
    '/api/assessments/$id/submit': {
      id: '/api/assessments/$id/submit'
      path: '/submit'
      fullPath: '/api/assessments/$id/submit'
      preLoaderRoute: typeof ApiAssessmentsIdSubmitRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/status': {
      id: '/api/assessments/$id/status'
      path: '/status'
      fullPath: '/api/assessments/$id/status'
      preLoaderRoute: typeof ApiAssessmentsIdStatusRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/retry': {
      id: '/api/assessments/$id/retry'
      path: '/retry'
      fullPath: '/api/assessments/$id/retry'
      preLoaderRoute: typeof ApiAssessmentsIdRetryRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/results': {
      id: '/api/assessments/$id/results'
      path: '/results'
      fullPath: '/api/assessments/$id/results'
      preLoaderRoute: typeof ApiAssessmentsIdResultsRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
    '/api/assessments/$id/advance': {
      id: '/api/assessments/$id/advance'
      path: '/advance'
      fullPath: '/api/assessments/$id/advance'
      preLoaderRoute: typeof ApiAssessmentsIdAdvanceRouteImport
      parentRoute: typeof ApiAssessmentsIdRoute
    }
  }
}

interface ApiAssessmentsIdRouteChildren {
  ApiAssessmentsIdAdvanceRoute: typeof ApiAssessmentsIdAdvanceRoute
  ApiAssessmentsIdResultsRoute: typeof ApiAssessmentsIdResultsRoute
  ApiAssessmentsIdRetryRoute: typeof ApiAssessmentsIdRetryRoute
  ApiAssessmentsIdStatusRoute: typeof ApiAssessmentsIdStatusRoute
  ApiAssessmentsIdSubmitRoute: typeof ApiAssessmentsIdSubmitRoute
}

const ApiAssessmentsIdRouteChildren: ApiAssessmentsIdRouteChildren = {
  ApiAssessmentsIdAdvanceRoute: ApiAssessmentsIdAdvanceRoute,
  ApiAssessmentsIdResultsRoute: ApiAssessmentsIdResultsRoute,
  ApiAssessmentsIdRetryRoute: ApiAssessmentsIdRetryRoute,
  ApiAssessmentsIdStatusRoute: ApiAssessmentsIdStatusRoute,
  ApiAssessmentsIdSubmitRoute: ApiAssessmentsIdSubmitRoute,
}

const ApiAssessmentsIdRouteWithChildren =
  ApiAssessmentsIdRoute._addFileChildren(ApiAssessmentsIdRouteChildren)

interface ApiAssessmentsRouteChildren {
  ApiAssessmentsIdRoute: typeof ApiAssessmentsIdRouteWithChildren
}

const ApiAssessmentsRouteChildren: ApiAssessmentsRouteChildren = {
  ApiAssessmentsIdRoute: ApiAssessmentsIdRouteWithChildren,
}

const ApiAssessmentsRouteWithChildren = ApiAssessmentsRoute._addFileChildren(
  ApiAssessmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssessmentsRoute: ApiAssessmentsRouteWithChildren,
  ObservationIdRoute: ObservationIdRoute,
  RuntimeObservationsRoute: RuntimeObservationsRoute,
  RuntimeSignalsRoute: RuntimeSignalsRoute,
  SignalIdRoute: SignalIdRoute,
  AssessmentIdObservationsRoute: AssessmentIdObservationsRoute,
  AssessmentIdProcessingRoute: AssessmentIdProcessingRoute,
  AssessmentIdResultsRoute: AssessmentIdResultsRoute,
  AssessmentIdSignalsRoute: AssessmentIdSignalsRoute,
  InternalObservationsIdRoute: InternalObservationsIdRoute,
  AssessmentIdIndexRoute: AssessmentIdIndexRoute,
  InternalObservationsIndexRoute: InternalObservationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
